Fix an AssertionError that could occur when processing malformed (but technically valid) metadata.
(backported from #8944)
